config/routes.rb
Rails.application.routes.draw do

 
  root 'home_page#home'
  
  
  devise_for :users ,:controllers => { :registration => "registration" }

  resources :home_page do
    resources :users
    devise_for :users
  end

  resources :communities do
    resources :users
    devise_for :users 
    resources :posts
    resources :comments
    
    
  end

  resources :users do 
    resources :comments
    resources :posts
    resources :contents
    resources :communities 
  end
  resources :categories
  resources :contents
  resources :comments

  resources :posts do
    resources :comments
    resources :communities
  end
  resources :resources  
  resources :scriptures 

  get "communities/new_post" => "communities/addPost", :as => :addPost

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :contents
	belongs_to :resource
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	


end

app/models/community.rb
class Community < ActiveRecord::Base

	scope :sorted, lambda {  order("name ASC")}
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    has_many :users
    has_many :posts, through: :users
    
 

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments ,dependent: :destroy
	belongs_to :user

	scope :first_name, lambda { where(:first_name => ["name LIKE ?", "%#{query}%"])}

	scope :sorted, lambda {  order("posts.id DESC")}
	scope :newest_first, lambda{ order("posts.created_at DESC")}
	scope :search, lambda{|query| where(["name LIKE ?", "%#{query}%"])}
end

app/models/resource.rb
class Resource < ActiveRecord::Base

	
	scope :sorted, lambda {  order("title ASC")}
	has_many :categories

	
end

app/models/scripture.rb
class Scripture < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

	
	belongs_to :community
	has_many :comments 
	has_many :contents
	has_many :posts ,dependent: :destroy

	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates :foreign_key
  scope :search, lambda{|query| where(["id LIKE ?", "%#{query}%"])}


end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :find_community

  # GET /users
  # GET /users.json
  def index   
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new({:community_id => :community_id})
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user.community = Community.find(params[:community_id])
    @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :controller => "community" , notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :phone, :avatar, :community_id)
    end

    def find_community
       if params[:community_id]
          @community=Community.find(params[:community_id])
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_for @user ,:html => {  :multipart => 'true' } do |f| %>

<div class="panel panel-warning">
  <div class="panel-heading">

    <h3 class="panel-title">Join Community 

    </tr></h3>
  </div>
  <div class="panel-body">
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <table class="table table-hover ">
    <tr>
    <td>
      <%= f.hidden_field :community_id, :value => @community.id %>
      
     <!--  @community.map { |c| [ c.name, c.id ] } -->
    </td>
    <td>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :first_name ,:autofocus => true  %>
    </td>
    <td>
      <%= f.text_field :last_name %>
    </td>
  </tr>
  <tr>
    <td>
     <%= f.password_field :password %>

   </td>
   <td>
     <%= f.password_field(:password_confirmation)%>
   </td>
 </tr>
 <tr>
  <td>
   <%= f.text_field :phone %>
 </td>
 <td>
  <%= f.text_field :email %>

</td>
</tr>
<tr>
  <td>     <%= f.file_field :avatar %></td>

  <td>  <%= f.submit :class =>'btn btn-primary btn-lg'%></td>
</tr>
</table>
<% end%>
</div>
</div>

<%= debug(@community)%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% @page_title  = 'Join'%>
<div class="header">
  <%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
 <p id="notice"><%= notice %></p>

<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>
<div id="footer" style="position:bottom;">
  <%= render(:partial => 'layouts/footer')%>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_community_user_path(@user) %> |
<%= link_to 'Back', community_users_path %>