config/routes.rb
Rails.application.routes.draw do

 
  root 'home_page#home'
  
  
  devise_for :users ,:controllers => { :registration => "registration" }

  resources :home_page do
    resources :users
    devise_for :users
  end

  resources :communities do
    resources :users
    devise_for :users 
    resources :posts
    resources :comments
    
    
  end

  resources :users do 
    resources :comments
    resources :posts
    resources :contents
    resources :communities 
  end
  resources :categories
  resources :contents
  resources :comments

  resources :posts do
    resources :comments
    resources :communities
  end
  resources :resources  
  resources :scriptures 

  get "communities/new_post" => "communities/addPost", :as => :addPost

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :contents
	belongs_to :resource
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	


end

app/models/community.rb
class Community < ActiveRecord::Base

	scope :sorted, lambda {  order("name ASC")}
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    has_many :users
    has_many :posts, through: :users
    
 

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments ,dependent: :destroy
	belongs_to :user

	scope :first_name, lambda { where(:first_name => ["name LIKE ?", "%#{query}%"])}

	scope :sorted, lambda {  order("posts.id DESC")}
	scope :newest_first, lambda{ order("posts.created_at DESC")}
	scope :search, lambda{|query| where(["name LIKE ?", "%#{query}%"])}
end

app/models/resource.rb
class Resource < ActiveRecord::Base

	
	scope :sorted, lambda {  order("title ASC")}
	has_many :categories

	
end

app/models/scripture.rb
class Scripture < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

	
	belongs_to :community
	has_many :comments 
	has_many :contents
	has_many :posts ,dependent: :destroy

	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates :foreign_key
  scope :search, lambda{|query| where(["id LIKE ?", "%#{query}%"])}


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container" >
		<p class="text-muted credit" style="text-align:center">&copy; (put in a year)Worship Harvest Community || designed &#64; <%= link_to("ruyonga", "http://twiiter.com/ruyonga")%> </p>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header" class="<%= 'active' if params[:controller] == 'home_page' %>" >
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <%= link_to("Worship Harvest Community", {:controller => 'home_page', :action=>'home'}, :class => 'navbar-brand')%>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
    <li class="<%= 'active' if params[:controller] == 'home_page' %>" ><a href="#">Home</a></li>
      <li class="<%= 'active' if params[:controller] == 'resources' %>"><%= link_to("Resources", {:controller => 'resources', :action => 'index'})%></li>
      <li class="<%= 'active' if params[:controller] == 'communities' %>"><%= link_to("Community", {:controller => 'communities', :action => 'index'})%></li>
    </ul>
    <form class="navbar-form navbar-left">
      <input class="form-control col-lg-8" placeholder="Search" type="text">
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li class="">

      <% if user_signed_in? %> 
       <%= link_to("Member logout",destroy_user_session_path, :method => :delete )%>
      <%else%>
        <%= link_to("Member Login",new_user_session_path )%>
      <%end%>
         </li>
      <li class="dropdown " class="<%= 'active' if params[:controller] == 'help' %>" >
        <a aria-expanded="true" href="#" class="dropdown-toggle" data-toggle="dropdown">Help<b class="caret"></b></a>
        <ul class="dropdown-menu">

          <li><a href="#">help</a></li>
          <li><a href="#">About the system</a></li>
          <li><a href="#">credits</a></li>
          
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_postForm.html.erb
<%= boostrap_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_slider.html.erb
  
<!-- <div id="sliderFrame"  >
    <div id="slider">
      
       
        
        

<%=image_tag('Defining-Missional-Communities_Milestone_Picture.jpg' ,size:"1200x550")%>
           
            
        </div>
        <div style="clear:both;height:0;"></div>
    </div> -->
    
<!-- class="hidden-xs"  -->

<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="carousel slide" id="carousel-502684">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-502684">
					</li>
					<li data-slide-to="1" data-target="#carousel-502684">
					</li>
					<li data-slide-to="2" data-target="#carousel-502684">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						 <%=image_tag('Defining-Missional-Communities_Milestone_Picture.jpg' ,size:"1600X400")%>
						<div class="carousel-caption">
							<h4>
								First Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<%=image_tag('home-banner-01.jpg' ,size:"1600X400")%>
						<div class="carousel-caption">
							<h4>
								Second Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<%=image_tag('rejoice.jpg' , size:"1600X400")%>
						<div class="carousel-caption">
							<h4>
								Third Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
					<div class="item">
						<%=image_tag('vidcam.jpg' , size:"1600X400")%>
						<div class="carousel-caption">
							<h4>
								Third Thumbnail label
							</h4>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
				</div> <a class="left carousel-control" href="#carousel-502684" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-502684" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "WHC | #{@page_title}" if @page_title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<% @page_title = "Edit Resource" %>
<div class="header">
<%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>
</div>
<div class="footer">
<%= render(:partial => 'layouts/footer')%>
</div>

app/views/resources/index.html.erb
<% @page_title = "Resources" %>
<div class="header">
  <%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
  <p id="notice"><%= notice %></p>

  <h1 style="text-align:center;">Community Resources</h1>
<!-- 
  <table>


    <tbody>
      <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></td>
        <td><%= resource.description %></td>
        <td><%= resource.published %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
-->
<br>
<table class=" table table-striped table-hover  ">
  <tbody>
    <tr class="active">
      <td>

       <div class="row featurette">
        <div class="col-md-7">
          <h3 class="featurette-heading"><%= link_to("Music","#")%></h3>
          <blockquote>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
          </blockquote>
        </div>
        <div class="col-md-5">
         <%=image_tag("music2.jpg", size:"200x200", class: "img-thumbnail" ,alt: "300x300")%>
       </div>
     </div>    
   </td>
   <td>
     <div class="row featurette">
      <div class="col-md-5">
        <%=image_tag('affinity.jpeg', size:"200x200" ,class: "img-thumbnail" ,alt: "300x300")%>
      </div>
      <div class="col-md-7">
        <h3 class="featurette-heading">Scriptures.</h3>
        <blockquote class="pull-right">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
        </blockquote>
      </div>
    </div>


  </td>
</tr>

<tr class="active">
  <td>

   <div class="row featurette">
    <div class="col-md-7">
      <h3 class="featurette-heading">Videos</h3>
      <blockquote>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
      </blockquote>
    </div>
    <div class="col-md-5">
     <%=image_tag("vidcam.jpg", size: "200x200", class: "img-thumbnail",alt: "300x300")%>
   </div>
 </div>    
</td>
<td>
 <div class="row featurette">
  <div class="col-md-5">
    <%=image_tag('youth.jpg', size:"200x200",class: "img-thumbnail"  ,alt: "300x300")%>
  </div>
  <div class="col-md-7">
    <h3 class="featurette-heading">Podcasts</h3>
    <blockquote class="pull-right">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
      <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
    </blockquote>
  </div>
</div>


</td>
</tr>
<tr class="active">
  <td>

   <div class="row featurette">
    <div class="col-md-7">
    <h3 class="featurette-heading">Testmony</h3>
      <blockquote>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
      </blockquote>
    </div>
    <div class="col-md-5">
     <%=image_tag("vidcam.jpg", size: "200x200", class: "img-thumbnail",alt: "300x300")%>
   </div>
 </div>    
</td>
<td>
 <div class="row featurette">
  <div class="col-md-5">
    <%=image_tag('go.jpg', size:"200x200",class: "img-thumbnail"  ,alt: "300x300")%>
  </div>
  <div class="col-md-7">
    <h3 class="featurette-heading">Inspirational Quotes</h3>
    <blockquote class="pull-right">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
      <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
    </blockquote>
  </div>
</div>


</td>
</tr>

</tbody>
</table>

<%= link_to 'New Resource', new_resource_path %>
</div>
<div class="footer">
  <%= render(:partial => 'layouts/footer')%>
</div>

app/views/resources/new.html.erb
<% @page_title = "New Resource Cat" %>
<div class="header">
<%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>
</div>
<div class="footer">
<%= render(:partial => 'layouts/footer')%>
</div>

app/views/resources/show.html.erb
<% @page_title = "Details" %>
<div class="header">
<%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @resource.published %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>
</div>
<div class="footer">
<%= render(:partial => 'layouts/footer')%>
</div>