config/routes.rb
Rails.application.routes.draw do

 
  root 'home_page#home'
  
  
  devise_for :users ,:controllers => { :registration => "registration" }

  resources :home_page do
    resources :users
    devise_for :users
  end

  resources :communities do
    resources :users
    devise_for :users 
    resources :posts
    resources :comments
    
    
  end

  resources :users do 
    resources :comments
    resources :posts
    resources :contents
    resources :communities 
  end
  resources :categories
  resources :contents
  resources :comments

  resources :posts do
    resources :comments
    resources :communities
  end
  resources :resources  
  resources :scriptures 

  get "communities/new_post" => "communities/addPost", :as => :addPost

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :contents
	belongs_to :resource
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	


end

app/models/community.rb
class Community < ActiveRecord::Base

	scope :sorted, lambda {  order("name ASC")}
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    has_many :users
    has_many :posts, through: :users
    
 

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments ,dependent: :destroy
	belongs_to :user

	scope :first_name, lambda { where(:first_name => ["name LIKE ?", "%#{query}%"])}

	scope :sorted, lambda {  order("posts.id DESC")}
	scope :newest_first, lambda{ order("posts.created_at DESC")}
	scope :search, lambda{|query| where(["name LIKE ?", "%#{query}%"])}
end

app/models/resource.rb
class Resource < ActiveRecord::Base

	
	scope :sorted, lambda {  order("title ASC")}
	has_many :categories

	
end

app/models/scripture.rb
class Scripture < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

	
	belongs_to :community
	has_many :comments 
	has_many :contents
	has_many :posts ,dependent: :destroy

	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates :foreign_key
  scope :search, lambda{|query| where(["id LIKE ?", "%#{query}%"])}


end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :find_community 
  # before_action :find_user


  # GET /posts
  # GET /posts.json
  def index
    # community_post = Community.find(params[:community_id])
    # @posts = community_post.posts
    @posts = Post.where(:community_id => @community)

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new

  @post = Post.new(:community_id => :community_id)
    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

     
     @post = Post.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to community_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author,:community_id,:user_id)
    end

    def find_community
       if params[:community_id]
          @community =Community.find(params[:community_id])
          puts @community
        end
    end

    def find_user
       if params[:user_id]
          @user =  User.find(params[:user_id])
          puts params[:user_id] 
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">

    <h3 class="panel-title">Make a Post

    </tr></h3>
  </div>
  <div class="panel-body">
<%= bootstrap_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :title %>
  </div>
  <div class="field">
  
    <%= f.text_area :body %>
  </div>
  <div class="field">

    <%= f.hidden_field :author , :value => current_user.first_name %>
     <%= f.hidden_field :community_id, :value => params[:community_id] %>
     <%= f.hidden_field :user_id, :value => current_user.id%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>
</div>
<%= debug(params[:community_id])%>
<%= debug(current_user.id)%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.author %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% @page_title= "Add Post"%>
<div class="header">
	<%= render(:partial => 'layouts/navbar')%>
</div>

<div class="main">
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

	
</div>


<div id="footer" style="position:bottom;">
	<%= render(:partial => 'layouts/footer')%>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back',post_communities_path(@post)%>