config/routes.rb
Rails.application.routes.draw do

 
  root 'home_page#home'
  
  
  devise_for :users ,:controllers => { :registration => "registration" }

  resources :home_page do
    resources :users
    devise_for :users
  end

  resources :communities do
    resources :users
    devise_for :users 
    resources :posts
    resources :comments
    
    
  end

  resources :users do 
    resources :comments
    resources :posts
    resources :contents
    resources :communities 
  end
  resources :categories
  resources :contents
  resources :comments

  resources :posts do
    resources :comments
    resources :communities
  end
  resources :resources  
  resources :scriptures 

  get "communities/new_post" => "communities/addPost", :as => :addPost

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :contents
	belongs_to :resource
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	


end

app/models/community.rb
class Community < ActiveRecord::Base

	scope :sorted, lambda {  order("name ASC")}
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    has_many :users
    has_many :posts, through: :users
    
 

end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments ,dependent: :destroy
	belongs_to :user

	scope :first_name, lambda { where(:first_name => ["name LIKE ?", "%#{query}%"])}

	scope :sorted, lambda {  order("posts.id DESC")}
	scope :newest_first, lambda{ order("posts.created_at DESC")}
	scope :search, lambda{|query| where(["name LIKE ?", "%#{query}%"])}
end

app/models/resource.rb
class Resource < ActiveRecord::Base

	
	scope :sorted, lambda {  order("title ASC")}
	has_many :categories

	
end

app/models/scripture.rb
class Scripture < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

	
	belongs_to :community
	has_many :comments 
	has_many :contents
	has_many :posts ,dependent: :destroy

	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates :foreign_key
  scope :search, lambda{|query| where(["id LIKE ?", "%#{query}%"])}


end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_filter :authenticate_user!, :except =>[:index]
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.sorted

  end

  # GET /communities/1
  # GET /communities/1.json
  def show
     # @communities = Community.includes(:posts => :comments).find(params[:id])
     # @posts = Community.find(params[:id]).posts
     # @comments = Community.find(params[:id]).posts.comments
    @posts = Post.where(:community_id => params[:id]).newest_first
    @comments = Comment.where(1)

    @comment = Comment.new(:post_id => :post_id)
   
     
  end

  # GET /communities/new
  def new
    @community = Community.new()
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def addPost
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :description, :fellowship, :leader,:avatar)
    end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/_addPost.hmtl.erb
<div class="modal hide fade" id="my-modal" title="My modal">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
    <h3 id="myModalLabel">New Post</h3>
  </div>
  <div class="modal-body a-unique-class">
   
  </div>
  <div class="modal-footer">
    <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
  </div>
</div>
</div>

app/views/communities/_form.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
  <h3 class="panel-title">Community Details</h3>
  </div>
  <div class="panel-body">

    <%= bootstrap_form_for @community, :html => {  :multipart => 'true' } do |f| %>
    <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% @community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">

      <%= f.text_field :name , placeholder: "Community Name"%>
    </div>
    <div class="field">

      <%= f.text_area :description, placeholder: "Full details about the community"%>
    </div>
    <div class="field">

      <%= f.text_field :fellowship, placeholder: "fellowship Days "%>
    </div>
    <div class="field">

      <%= f.text_field :leader %>
    </div>
    <div class="field">

     <%= f.file_field :avatar %>
   </div>

   <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

</div>
</div>

app/views/communities/addPost.js.erb
$("#modal-window").html("<%= escape_javascript(render 'communities/addPost') %>");

app/views/communities/edit.html.erb
<% @page_title = "Edit Community" %>
<div class="header">
	<%= render(:partial => 'layouts/navbar')%>
</div>
<h1>Editing Community</h1>
<div class="col-md-8">

	<%= render 'form' %>

	<%= link_to 'Show', @community %> |
	<%= link_to 'Back', communities_path %>


	<div class="footer">
		<%= render(:partial => 'layouts/footer')%>
	</div>
</div>

app/views/communities/index.html.erb
<% @page_title  = 'Communities'%>
<div class="header">
  <%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
 <p id="notice"><%= notice %></p>

 <h1 style="text-align:center; ">Our Missional Communities</h1>
 <div class="well well-sm" >
  <marquee> Join a missional Community Today and help in spreading the word of God</marquee>
</div>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="row clearfix">
        <div class="col-md-8 column">
         <% @communities.each do |community|%>
         <div class="panel panel-warning table-striped table-hover ">
          <div class="panel-heading"><%=link_to( community.name + ' Missional Community' , community, :class =>"btn btn-default")%>
          </div>
          <div class="panel-body">
            <div class="row featurette">
              <div class="col-md-7 column">        
                <p><%= community.description %></p>
                <br />
                Fellowship on: <em><%= community.fellowship%></em> <br />
                Leader:<em> <%= community.leader %></em>  <br />

                <% if user_signed_in? %>
                 <%= link_to("Join G12",  new_community_user_path(:community_id), :class =>"btn btn-success")%> 
                 <%= link_to("Mak a Post",  addPost_path ,:class => "btn btn-primary", :remote => true, data: {toggle: "modal", target: "#modal"} )%>

                 <%else%>
                   <%= link_to("Join Us",new_community_user_path(community.id), :class =>"btn btn-default")%>
                 <%end%>

                   
                <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  
                </div>

              </div>

              <div class="col-md-5">

               <%= image_tag(community.avatar.url(:medium), class: "img-thumbnail" ,alt: "300x300" )%>
             </div>
           </div>      
         </div>
       </div>
       <%end%>
     </div>
     <div class="col-md-4 column">
       <div class="list-group" >
        <a href="#" class="list-group-item active">
          Up Comming Community Events
        </a>
        <a href="#" class="list-group-item"> Vising the Ederly
        </a>
        <a href="#" class="list-group-item">Morbi leo risus
        </a>
      </div>
    </div>
  </div>
</div>
</div>
</div>


<div id="footer" style="position:bottom;">
  <%= render(:partial => 'layouts/footer')%>
</div>
<!-- :remote => true, data: {toggle: "modal", target: "#modal"} -->

app/views/communities/new.html.erb
<% @page_title= "Add Community"%>
<div class="header">
	<%= render(:partial => 'layouts/navbar')%>
</div>
<h1>Add Community</h1>
<div class="col-md-8">
	<%= render 'form' %>

	<%= link_to 'Back', communities_path %>
</div>
<div class="col-md-4">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Admin Tasks</h3>
		</div>
		<div class="panel-body">
			
		</div>
	</div>
	
</div>


<div id="footer" style="position:bottom;">
	<%= render(:partial => 'layouts/footer')%>
</div>

app/views/communities/show.html.erb
<% @page_title = @community.name  %>
<div class="header">
	<%= render(:partial => 'layouts/navbar')%>
</div>
<div class="main">
	<div class="container" >
		<div class="row clearfix">
			<div class="col-md-12 column">
				<div class="jumbotron show" >

					<%= image_tag(@community.avatar.url(:medium), size: "400X300", class: "screenshot" ,alt: "avatar")%>
					<div class="details">
						<p id="notice"><%= notice %></p>
						<div class="title">
							<h1>  <%= @community.name + " Missional Community"%></h1></div>
							<%= @community.description %><br />
							<%= @community.fellowship %><br />
							<%= @community.leader %>
							<p>
								<% if user_signed_in? %>
								<%= link_to("Join G12",  new_community_user_path(:community_id), :class =>"btn btn-success")%> 
								<%= link_to("Mak a Post",  new_community_post_path(@community,current_user),:class => "btn btn-primary",)%>
								<%else%>
								<%= link_to("Join Us",new_community_user_path(@community.id), :class =>"btn btn-default")%>
								<%end%>


							</p>
						</div>
					</div>
				</div>
				<div class="row clearfix">
					<div class="col-md-8 column">
						<% @posts.each do |post|%>
						<div class="media well">
							<a href="#" class="pull-left"><img src="http://lorempixel.com/64/64/" class="media-object" alt='' />

							</a>
							<%= post.author%>
							<div class="media-body">

								<h4 class="media-heading">
									<%= link_to(post.title, edit_community_post_path(@community.id, post.id))%>
								</h4> 
								<p>
									<%= post.body %>
									<div>										
										<% 
										@comments = Comment.where(:post_id => post.id)
										@comments.each do |comment| %>
										<% @user = comment.user_id%>


										<div class="media">
											<%= image_tag(current_user.avatar.url(:thumb), size: "400X300", class: "pull-left" ,alt: "avatar")%>
											<div class="media-body">
												<h4 class="media-heading">
													<%= link_to( comment.author, "#") %>
												</h4>	<%= comment.body %>
											</div>
										</div>
										<%end%>
									</div>
									<%= link_to("Add Comment", new_post_comment_path(post.id))%>

									<%= render(:partial =>"comments/form",:locals =>{:comment => @comment, :post_id => post.id}) %>
								</p>

							</div> 
						</div>
						<%end%>
					</div>































					<div class="col-md-4 column">
						<div class="list-group">
							<a href="#" class="list-group-item active">Home</a>
							<div class="list-group-item">
								List header
							</div>
							<div class="list-group-item">
								<h4 class="list-group-item-heading">
									List group item heading
								</h4>
								<p class="list-group-item-text">
									...
								</p>
							</div>
							<div class="list-group-item">
								<span class="badge">14</span>Help
							</div> <a class="list-group-item active"><span class="badge">14</span>Help</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%= link_to 'Edit', edit_community_path(@community), :class=>"btn btn-default"%> |
	<%= link_to 'Back', communities_path,:class=>"btn btn-default" %>

	<div class="footer">
		<%= render(:partial => 'layouts/footer')%>
	</div>
</div>